In [2]:
import numpy as np

In [3]:
first_numpy_arr = np.array([1,2,3,4])

In [5]:
print(first_numpy_arr)

[1 2 3 4]


In [8]:
arr_with_zero = np.zeros((5,3))
arr_with_zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
arr_with_one = np.ones((5,5))
arr_with_one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
empty_arr = np.empty((3,5))
empty_arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np_arange = np.arange(12)

In [24]:
print(np_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [27]:
np_arange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
np_linspce = np.linspace(1,6,5)

In [30]:
print(np_linspce)

[1.   2.25 3.5  4.75 6.  ]


In [33]:
oneD_arr = np.arange(15)

In [34]:
print(oneD_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [36]:
twoD_arr = oneD_arr.reshape(3,5)

In [37]:
print(twoD_arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [40]:
threeD_arr = np.arange(27).reshape(3,3,3)

In [41]:
print(threeD_arr)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [42]:
np.array(24)

array(24)

In [43]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [44]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,5,6]]])

array([[[1, 1, 1],
        [2, 2, 2]],

       [[3, 3, 3],
        [4, 5, 6]]])

In [47]:
arr = np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,5,6]]])

In [48]:
arr.shape

(2, 2, 3)

In [49]:
arr.size

12

In [50]:
arr.ndim #number of dimensions

3

In [51]:
n_arr = np.array([x for x in range(1,10)])
n_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
n_arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
n_arr = np.array([x for x in range(1,13)])
n_arr.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [57]:
n_arr = np.array([x for x in range(1,13)])
n_arr.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [58]:
#automatically calculate the last dimension using -1
n_arr.reshape(2,2,-1)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [59]:
n_arr = n_arr.reshape(3,2,2)
n_arr

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [60]:
#flatten the array into one dimension
n_arr.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [61]:
A = np.array([[1,2,1],[2,2,3]])
B = np.array([3,4,5])

In [62]:
np.add(A,B)

array([[4, 6, 6],
       [5, 6, 8]])

In [63]:
np.subtract(B,A)

array([[2, 2, 4],
       [1, 2, 2]])

In [64]:
np.multiply(A,B)

array([[ 3,  8,  5],
       [ 6,  8, 15]])

In [65]:
np.divide(A,B)

array([[0.33333333, 0.5       , 0.2       ],
       [0.66666667, 0.5       , 0.6       ]])

In [66]:
np.power(A,2)

array([[1, 4, 1],
       [4, 4, 9]], dtype=int32)

In [67]:
np.power(A,B)

array([[  1,  16,   1],
       [  8,  16, 243]])

In [70]:
#Conditional Statements
x = np.array([x for x in range(12)])
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [71]:
np.where(x%2==0,'Even','Odd')

array(['Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd', 'Even', 'Odd'], dtype='<U4')

In [72]:
condition_list = [x<5,x>5]
#if x<5 calculate the square of x, else if x>5 calculate the cube of x
choice_list = [x**2,x**3]

In [74]:
#pass the condition list and choiselist also assign a default value if the condition is not satisfied in the list
np.select(condition_list,choice_list,default=x)

array([   0,    1,    4,    9,   16,    5,  216,  343,  512,  729, 1000,
       1331])

In [75]:
#Common mathematical and statistical functions in NumPy
arr = np.array([[4,3,2],[10,1,0],[5,8,24]])
arr

array([[ 4,  3,  2],
       [10,  1,  0],
       [ 5,  8, 24]])

In [76]:
np.amin(arr)

0

In [77]:
np.amin(arr, axis=0)

array([4, 1, 0])

In [78]:
np.amin(arr, axis=1)

array([2, 0, 5])

In [79]:
np.max(arr)

24

In [80]:
np.amax(arr, axis=0)

array([10,  8, 24])

In [81]:
np.amax(arr, axis=1)

array([ 4, 10, 24])

In [82]:
np.median(arr)

4.0

In [83]:
np.mean(arr)

6.333333333333333

In [84]:
np.std(arr)

6.944222218666553

In [85]:
np.var(arr)

48.22222222222222

In [87]:
np.percentile(arr, 50)

4.0

In [88]:
degrees = np.array([0, 30, 45, 60, 90])

In [90]:
np.sin(degrees*np.pi/180)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [91]:
np.cos(degrees*np.pi/180)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [92]:
np.tan(degrees*np.pi/180)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [93]:
np.arcsin(degrees*np.pi/180)

array([0.        , 0.55106958, 0.90333911,        nan,        nan])

In [94]:
np.arccos(degrees*np.pi/180)

array([1.57079633, 1.01972674, 0.66745722,        nan,        nan])

In [95]:
np.arctan(degrees*np.pi/180)

array([0.        , 0.48234791, 0.66577375, 0.80844879, 1.00388482])

In [96]:
arr = np.array([0.1, 0.8, -2.2, -9.87])
np.floor(arr)

array([  0.,   0.,  -3., -10.])

In [97]:
np.ceil(arr)

array([ 1.,  1., -2., -9.])

In [98]:
#Indexing
one_d = np.array([1, 2, 3, 4, 5, 6])
two_d = np.array([[1, 2, 3], [4, 5, 6]])
three_d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [101]:
#return first element of one dimension array
one_d[0]

1

In [102]:
#return second element of one dimension array
one_d[1]

2

In [104]:
#return second element of one dimension array in reverse
one_d[-2]

5

In [105]:
#return first element of the first array in two dimension array 
two_d[0, 0]

1

In [111]:
#return first element of the third array in two dimension array 
two_d[0, 2]

3

In [113]:
#return first element in reverse of the second array in two dimension array
two_d[1, -1]

6

In [114]:
#return third element in the second array of the first array in three dimension array
three_d[0, 1, 2]

6

In [115]:
#return first element in reverse in the second array of the second array in three dimension array
three_d[1, 1, -1]

12

In [116]:
#Slicing
one_d = np.array([1, 2, 3, 4, 5, 6])
two_d = np.array([[1, 2, 3], [4, 5, 6]])
three_d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [117]:
#sliced the first index to the end of the list
one_d[1:]

array([2, 3, 4, 5, 6])

In [120]:
#sliced the third index to the fifth index of the list
one_d[3:5]

array([4, 5])

In [123]:
#sliced the fourth element to the fifth element of the list
one_d[-3:-1]

array([4, 5])

In [124]:
#specify the row and column for two dimension
two_d

array([[1, 2, 3],
       [4, 5, 6]])

In [126]:
#sliced the second array starting from the first element to the end
two_d[1,1:]

array([5, 6])

In [127]:
two_d[-2:-3:-1]

array([[1, 2, 3]])

In [129]:
#first array then sliced from the first array in the first array then first element of the second array
three_d[0,1:,1:]

array([[5, 6]])